export enum Role {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ADMIN = 'ROLE_ADMIN',
  MANAGER = 'ROLE_MANAGER',
  USER_EMPLOYEE = 'ROLE_USER',
  IT_MANAGER='ROLE_IT',
  FINANCE_MANAGER="ROLE_FINANCE",
  HR_MANAGER = 'ROLE_HR'
}
